<?php
// Fetch all holidays of 2026
$holidayDates = [];
if (isset($pdo)) {
    try {
        $stmt = $pdo->prepare("SELECT event_date FROM events WHERE type = 'holiday' AND YEAR(event_date) = 2026");
        $stmt->execute();
        $holidayDates = $stmt->fetchAll(PDO::FETCH_COLUMN);
    } catch (Exception $e) {
        // Silent fail
    }
}
?>
<script>
const nationalHolidays = <?php echo json_encode($holidayDates); ?>;
</script>

<!-- Employee Apply Leave Modal -->
<div id="leaveModal" class="modal-overlay">
    <div class="modal-content">
        <span class="close" onclick="closeModal('leaveModal')">&times;</span>
        <h2 style="margin-bottom: 1rem; color: var(--primary-color);">Apply for Leave</h2>
        <form action="apply_leave.php" method="POST" enctype="multipart/form-data" onsubmit="return validateLeaveForm()">
            <!-- Hidden context fields for redirect -->
            <input type="hidden" name="nav_month" value="<?php echo $navMonth; ?>">
            <input type="hidden" name="nav_year" value="<?php echo $navYear; ?>">
            <div class="form-grid" style="grid-template-columns: 1fr 1fr; gap: 1rem; margin-bottom: 1rem;">
                <div class="form-group">
                    <label>From Date <span style="color:red">*</span></label>
                    <input type="date" name="from_date" id="modalFromDate" required onchange="handleFromDateChange()">
                </div>
                <div class="form-group">
                    <label>To Date <span style="color:red">*</span></label>
                    <input type="date" name="to_date" id="modalToDate" required onchange="calculateDays()">
                </div>
            </div>

            <div id="daysCountDisplay" style="margin-bottom: 1rem; font-size: 0.9rem; color: var(--text-muted); font-weight: 600;">
                Total Days: <span id="totalDaysText">0</span>
            </div>

            <div class="form-group">
                <label>Subject <span style="color:red">*</span></label>
                <input type="text" name="subject" required placeholder="e.g. Sick Leave, Vacation">
            </div>

            <div class="form-group">
                <label>Description <span style="color:red">*</span></label>
                <textarea name="description" required
                    style="width:100%; min-height:80px; padding:0.75rem; border:1px solid var(--border-color); border-radius:0.5rem;"
                    placeholder="Reason for leave..."></textarea>
            </div>

            <div class="form-group">
                <label>Attachment (Optional)</label>
                <input type="file" name="attachment">
            </div>

            <button type="submit" class="btn btn-primary" style="width:100%; padding:0.8rem;">Send Request</button>
        </form>
    </div>
</div>

<!-- Admin View Leave Modal -->
<div id="adminLeaveModal" class="modal-overlay">
    <div class="modal-content">
        <span class="close" onclick="closeModal('adminLeaveModal')">&times;</span>
        <h2 style="margin-bottom: 0.5rem; color: var(--primary-color);">Leave Request Details</h2>
        <p id="leaveStatusBadge" style="display:inline-block; margin-bottom:1.5rem;"></p>

        <form action="process_leave.php" method="POST" id="approvalForm">
            <input type="hidden" name="leave_id" id="processLeaveId">
            <input type="hidden" name="status" id="processStatus" value="approved">

            <div id="leaveDetailContent">
                <p><strong>Employee:</strong> <span id="viewEmpName"></span></p>
                <p><strong>Range:</strong> <span id="viewLeaveRange"></span></p>
                <p><strong>Subject:</strong> <span id="viewSubject"></span></p>
                <hr style="margin:1rem 0; border:0; border-top:1px solid var(--border-color);">
                
                <div id="partialApprovalSection" style="margin-bottom: 1.5rem;">
                    <p style="font-weight: 700; margin-bottom: 0.5rem;">Select Days to Approve:</p>
                    <div id="daysChecklist" style="display: grid; grid-template-columns: repeat(auto-fill, minmax(140px, 1fr)); gap: 0.5rem; background: #f8fafc; padding: 1rem; border-radius: 0.5rem; border: 1px solid var(--border-color);">
                        <!-- Checkboxes generated by JS -->
                    </div>
                </div>

                <p><strong>Description:</strong></p>
                <p id="viewDescription" style="background:#f8fafc; padding:1rem; border-radius:0.5rem; margin-top:0.5rem; margin-bottom: 1rem;">
                </p>

                <div id="viewAttachmentArea" style="margin-top:1rem; margin-bottom: 1rem;">
                    <strong>Attachment:</strong> <a id="viewAttachmentLink" href="#" target="_blank"
                        style="color:var(--primary-color);">View File</a>
                    <span id="noAttachmentMsg" style="color:var(--text-muted);">No attachment</span>
                </div>
            </div>

            <div id="adminActions" style="display: flex; gap: 1rem; margin-top: 2rem;">
                <button type="submit" class="btn" onclick="document.getElementById('processStatus').value='approved'"
                    style="background:#16a34a; color:white; flex:1; border:none; padding: 1rem;">Approve Selected Days</button>
                <button type="submit" class="btn" onclick="document.getElementById('processStatus').value='rejected'"
                    style="background:#ef4444; color:white; flex:1; border:none; padding: 1rem;">Reject All</button>
            </div>
        </form>
    </div>
</div>

<style>
    .close {
        position: absolute;
        right: 1.5rem;
        top: 1rem;
        color: #aaa;
        font-size: 28px;
        font-weight: bold;
        cursor: pointer;
    }

    .close:hover {
        color: black;
    }

    .status-badge {
        padding: 0.25rem 0.75rem;
        border-radius: 2rem;
        font-size: 0.85rem;
        font-weight: 600;
    }

    .status-pending { background: #fef9c3; color: #a16207; }
    .status-approved { background: #dcfce7; color: #16a34a; }
    .status-partially_approved { background: #dbeafe; color: #1d4ed8; }
    .status-rejected { background: #fee2e2; color: #ef4444; }

    .day-checkbox-item {
        display: flex;
        align-items: center;
        gap: 0.5rem;
        font-size: 0.85rem;
        cursor: pointer;
    }
    .day-checkbox-item input { cursor: pointer; }
</style>

<script>
    function isHolidayOrWeekendJS(dateStr) {
        const dateObj = new Date(dateStr);
        const day = dateObj.getDay(); // 0=Sun, 6=Sat
        if (day === 0 || day === 6) {
            return true;
        }
        return nationalHolidays.includes(dateStr);
    }

    function validateLeaveForm() {
        const from = document.getElementById('modalFromDate').value;
        const to = document.getElementById('modalToDate').value;
        
        if (!from || !to) return false;
        
        if (isHolidayOrWeekendJS(from)) {
            alert("Error: Cannot start leave on a weekend or national holiday.");
            return false;
        }
        if (isHolidayOrWeekendJS(to)) {
            alert("Error: Cannot end leave on a weekend or national holiday.");
            return false;
        }
        
        // Count total valid working days in the range
        let start = new Date(from);
        let end = new Date(to);
        let validDays = 0;
        let cur = new Date(start);
        while (cur <= end) {
            let y = cur.getFullYear();
            let m = String(cur.getMonth() + 1).padStart(2, '0');
            let d = String(cur.getDate()).padStart(2, '0');
            let dateStr = `${y}-${m}-${d}`;
            
            let day = cur.getDay();
            if (day !== 0 && day !== 6 && !nationalHolidays.includes(dateStr)) {
                validDays++;
            }
            cur.setDate(cur.getDate() + 1);
        }
        
        if (validDays === 0) {
            alert("Error: Your selected range contains only weekends or national holidays.");
            return false;
        }
        
        return true;
    }

    function handleFromDateChange() {
        const fromDateInput = document.getElementById('modalFromDate');
        const toDateInput = document.getElementById('modalToDate');
        
        if (fromDateInput.value) {
            toDateInput.setAttribute('min', fromDateInput.value);
            if (toDateInput.value && toDateInput.value < fromDateInput.value) {
                toDateInput.value = fromDateInput.value;
            }
        }
        calculateDays();
    }

    function openLeaveModal(date) {
        document.getElementById('modalFromDate').value = date;
        document.getElementById('modalToDate').value = date;
        
        const today = new Date();
        const year = today.getFullYear();
        const month = String(today.getMonth() + 1).padStart(2, '0');
        const day = String(today.getDate()).padStart(2, '0');
        const minDate = `${year}-${month}-${day}`;
        
        document.getElementById('modalFromDate').setAttribute('min', minDate);
        
        handleFromDateChange();
        
        document.getElementById('leaveModal').classList.add('active');
        document.body.style.overflow = 'hidden';
    }

    function calculateDays() {
        const from = document.getElementById('modalFromDate').value;
        const to = document.getElementById('modalToDate').value;
        if (from && to) {
            let start = new Date(from);
            let end = new Date(to);
            let count = 0;
            let cur = new Date(start);
            while (cur <= end) {
                let y = cur.getFullYear();
                let m = String(cur.getMonth() + 1).padStart(2, '0');
                let d = String(cur.getDate()).padStart(2, '0');
                let dateStr = `${y}-${m}-${d}`;
                
                let day = cur.getDay(); // 0=Sun, 6=Sat
                if (day !== 0 && day !== 6 && !nationalHolidays.includes(dateStr)) {
                    count++;
                }
                cur.setDate(cur.getDate() + 1);
            }
            document.getElementById('totalDaysText').innerText = count;
        }
    }

    function openAdminViewModal(data) {
        document.getElementById('viewEmpName').innerText = data.user_name;
        document.getElementById('viewLeaveRange').innerText = data.from_date + ' to ' + data.to_date;
        document.getElementById('viewSubject').innerText = data.subject;
        document.getElementById('viewDescription').innerText = data.description;
        document.getElementById('processLeaveId').value = data.id;

        const badge = document.getElementById('leaveStatusBadge');
        badge.innerText = data.status.replace('_', ' ').toUpperCase();
        badge.className = 'status-badge status-' + data.status;

        // Generate Day Checklist
        const checklist = document.getElementById('daysChecklist');
        checklist.innerHTML = '';
        
        const start = new Date(data.from_date);
        const end = new Date(data.to_date);
        
        // Loop through dates
        for (let d = new Date(start); d <= end; d.setDate(d.getDate() + 1)) {
            const dateStr = d.toISOString().split('T')[0];
            const displayDate = d.toLocaleDateString('en-GB', { day: '2-digit', month: 'short' });
            const dayNum = d.getDay(); // 0=Sun, 6=Sat

            // Deduct Holidays (Weekends)
            if (dayNum === 0 || dayNum === 6) continue;
            
            const div = document.createElement('div');
            div.className = 'day-checkbox-item';
            
            const checkedAttr = (data.status === 'pending') ? 'checked' : (data.approved_dates && data.approved_dates.includes(dateStr) ? 'checked' : '');
            const disabledAttr = (data.status !== 'pending') ? 'disabled' : '';

            div.innerHTML = `
                <input type="checkbox" name="approved_days[]" value="${dateStr}" ${checkedAttr} ${disabledAttr}>
                <span>${displayDate}</span>
            `;
            checklist.appendChild(div);
        }

        // Hide/Show partial approval section based on status
        document.getElementById('partialApprovalSection').style.display = 'block';

        const attachmentLink = document.getElementById('viewAttachmentLink');
        const noAttachmentMsg = document.getElementById('noAttachmentMsg');
        if (data.attachment) {
            attachmentLink.href = 'uploads/leaves/' + data.attachment;
            attachmentLink.style.display = 'inline';
            noAttachmentMsg.style.display = 'none';
        } else {
            attachmentLink.style.display = 'none';
            noAttachmentMsg.style.display = 'inline';
        }

        document.getElementById('adminActions').style.display = (data.status === 'pending') ? 'flex' : 'none';
        document.getElementById('adminLeaveModal').classList.add('active');
        document.body.style.overflow = 'hidden';
    }

    function closeModal(id) {
        document.getElementById(id).classList.remove('active');
        document.body.style.overflow = 'auto';
    }

    window.onclick = function (event) {
        if (event.target.classList.contains('modal-overlay')) {
            event.target.classList.remove('active');
            document.body.style.overflow = 'auto';
        }
    }
</script>